# Generated by Django 5.2.4 on 2025-07-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoexcel',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
